INSERT INTO municipios (municipio, id_estado) VALUES
('Durango', 10),
('Gómez Palacio', 10),
('Lerdo', 10),
('Canatlán', 10),
('Canelas', 10),
('Coneto de Comonfort', 10),
('Cuencamé', 10),
('Durango', 10),
('General Simón Bolívar', 10),
('Guanaceví', 10),
('Guadalupe Victoria', 10),
('Hidalgo', 10),
('Indé', 10),
('Mapimí', 10),
('Mezquital', 10),
('Nazas', 10),
('Nombre de Dios', 10),
('Ocampo', 10),
('El Oro', 10),
('Otáez', 10),
('Pánuco de Coronado', 10),
('Peñón Blanco', 10),
('Poanas', 10),
('Pueblo Nuevo', 10),
('Rodeo', 10),
('San Bernardo', 10),
('San Dimas', 10),
('San Juan de Guadalupe', 10),
('San Juan del Río', 10),
('San Luis del Cordero', 10),
('San Pedro del Gallo', 10),
('Santa Clara', 10),
('Santiago Papasquiaro', 10),
('Súchil', 10),
('Tamazula', 10),
('Tepehuanes', 10),
('Tlahualilo', 10),
('Topia', 10),
('Vicente Guerrero', 10),
('Nuevo Ideal', 10);
